### ISSUE TITLE
pure function - don't touch feed object.

### ISSUE THREAD

**Issue by dominictarr** [ssbc/ssb-msg-schemas#1]
this could be a bit cleaner if it didn't touch the feed object. The trouble is if I see `schemas.addFollow(feed, content, cb)` it's not obvious how schemas interacts with feed.
I read the code and saw that it didn't interact with feed except by calling add (which is what I guessed, but I had to read the code to know for sure)

However, if this module just created a valid message you could use it like this:
`feed.add(schemas.follow(content, cb))` and it would be the same number of characters, but instantly obvious that schemas is a pure function that returns a value.

**Comment by pfrazee** [comment]
that cant quite work, the cb would need to go somewhere. we could do...

`feed.add(schemas.follow(bob), cb)` and have `follow` throw if there's an error

or 

``` js
var follow = schemas.follow(bob)
if (follow instanceof Error)
  // handle
feed.add(follow, cb)
```

or modify feed.add to do the error check and call the `cb` with it if its an error

**Comment by dominictarr** [comment]
oops, I meant to say:
`feed.add(schemas.follow(content), cb)`

I think it would be more conventional to have the schema create methods throw if they do not have enough data to create a valid message.

**Comment by pfrazee** [comment]
recopying below, github apparently doesnt do markdown when it comes from emails

**Comment by pfrazee** [comment]
hmm, you'd get a lot of code that looks like

``` js
try {
  feed.add(schemas.follow(bob), function (err) {
    if (err) handleErr(err)
  })
} catch (e) {
  handleErr(err)
}
```

a `feed.add` error would indicate either a connection loss or something, i
guess, fundamentally fubared. if it's a connection error, that would be
handled elsewhere, so you could just return on error and keep the gui in
the same state

``` js
try {
  feed.add(schemas.follow(bob), function (err) {
    if (err) return
  })
} catch (e) {
  handleErr(err)
}
```

that's not so ugly - is it safe?

**Comment by dominictarr** [comment]
it would be much better to not put the `feed.add` inside the try,

``` js
var msg
try { msg = schemas.follow(bob) }
catch (err) { return cb(err) }
feed.add(msg, cb)
```

`try..catch` is ugly, but it's javascript.

If you really wanted to it could abstracted out into a simple function:

``` js
function checkAndAdd(feed, schema, args, cb) {
  try { msg = schema.apply(null, args }
  catch (err) { return cb(err) }
  feed.add(msg, cb)
}
//then use it with
checkAndAdd(feed, schema.follow, [bob], cb)
```

another way we could do it is return null on invalid
and then set `schema.reason = error messages`
but that is a bit weird.

**Comment by pfrazee** [comment]
wish we didnt have to use that try catch. if i think of something better before tomorrow i'll post it

**Comment by pfrazee** [comment]
no longer relevant
