### ISSUE TITLE
@mentions are awkward around punctuation.

### ISSUE THREAD

**Issue by dominictarr** [ssbc/ssb-msg-schemas#15]
I can't put a mention at the start of quotes etc, "@paul something something" because " interfers.
Also, if I edit stuff around the mention, I'm never really sure if the link is actually there,
because the text box only has a mutable mention - the name is there, and then the active link is separate data.

this means the markdown text is not enough on it's own, you must also have the mentions array. although, for other mention types (messages and blobs) the link IS in the markdown, so we are sweet.

the natural robust solution seems to be to make a user mention be a markdown link `[@name](pubkey)`
this has several advantages, it's much simpler to put everything in the markdown, but one obvious disadvantage - now mentioning someone takes up a bunch more space in the editor.

two ideas:
- easy, just substring the pubkey to a few chars, so it's not too big (replace when they hit send)
- smarter editor, content editable or something, which would render links without this visual overhead.

media savy but untechnical users are totally used to weird looking links (as we have observed in our own user studies) but weird looking links for users is not familiar, since normally @ mentions are a part of a unique username silo, such as twitter, or github for that matter.

**Comment by dominictarr** [comment]
wasn't sure if I should post this here or on suggest-box? I think both would need to change if we where to changes this, as I recall suggest-box relies on spaces to separate words.

**Comment by pfrazee** [comment]
> although, for other mention types (messages and blobs) the link IS in the markdown, so we are sweet.

That's not required, if it picks up a reference in there it will auto-link it. (/pedantic)

I think this is probably a good idea, though. And a wysiwyg would be a good idea anyway, for a wider audience.

**Comment by dominictarr** [comment]
@pfraze that gives you a link straight to the object, without any human-readable text, right? does that work for images?

**Comment by dominictarr** [comment]
I mean, does it embed the images correctly?

**Comment by pfrazee** [comment]
No just the straight link. If there's metadata somewhere on the message with an image content-type, we could make it embed. Or we might build up an internal blobs metadata-store that uses https://www.npmjs.com/package/pull-identify-filetype.
