### ISSUE TITLE
Photo-collection message type

### ISSUE THREAD

**Issue by pfrazee** [ssbc/ssb-msg-schemas#9]
We need a message type for an album of photos

Requirements:
- Provides a list of photos
- Need to be able to add and remove photos, or update metadata, after initial publish
- Collection metadata:
  - title
  - primary/cover photo
  - description
- Photo metadata:
  - name
  - size
  - mimetype
  - width
  - height
  - description

For simplicity, the type will not support:
- Multiple authors
- Photo order

Multiple authors could be supported using CRDTs, but it would be complex. For instance, a OR set would be great for controlling the list of photos, but not for controlling the metadata on the collection, or the metadata on the photos themselves. Given that we may not use multiple authors, or may simply funnel changes by other users through an owner user, it's better not to bother with the CRDTs.

**Comment by pfrazee** [comment]
Schema proposal.

``` js
{
  type: 'image-collection',
  updates: {
    link: MsgRef, // if this is an update, points to the original collection msg
    deleted: Boolean // is the target deleted? defaults to false
  },
  title: String,
  desc: String,
  image: BlobLink, // the cover photo
  includes: [{
    link: BlobRef,
    name: String,
    desc: String,
    size: Number, // in bytes
    width: Number,
    height: Number,
    type: String // mimetype
  }],
  excludes: BlobLinks
}
```

This is based on a CRUD pattern. Here are the rules:
- Collections are created by publishing a `photo-collection` with no `updates` or `redacts` link.
- Collections are updated by populating the `updates` link with a ref to the target collection.
- Collections are "deleted" by populating the `updates` link with a ref to the target collection, and setting `updates.deleted` to `true`. (Whether it can be undeleted depends on whether we want to create a garbage-collection protocol around this info.)
- In both create and update messages, the following rules apply:
  - Collection metadata (title, desc, image) are overwritten if the message has a value for them. If left out, the values are unchanged.
  - Images are added if present in the `includes` links, and removed if present in `excludes`. If an image is present in both in a message, then `includes` wins.
  - Image metadata (name, desc, size, width, height, and type) are overwritten if the message has a value for them. If left out, the values are unchanged.

Images are identified by their blob hashes. If an update-message includes a link to an image hash which was already present in the collection, the values attached to the link in the update-message will overwrite previous values on the image.

Here is an example set of messages:

``` js
{
  type: 'image-collection',
  title: 'Pauls Rocking Album',
  desc: 'this is my album, and its totally awesome',
  image: '&hash2',
  includes: [
    { link: '&hash1', name: 'foo.png', desc: 'some foo thing', size: 40000, width: 256, height: 256, type: 'image/png' },
    { link: '&hash2', name: 'bar.png', size: 20000, width: 128, height: 128, type: 'image/png' }
  ]
}
```

That creates an album with 2 messages, using the 2nd message as the cover. I decide to remove image 1 and to add a description to image 2:

``` js
{
  type: 'image-collection',
  updates: '%collectionhash',
  includes: { link: '&hash2', desc: 'ok now this has a desc' }
  excludes: '&hash1'
}
```

And then I decide this whole album was a bad idea, so I "delete" it:

``` js
{
  type: 'image-collection',
  updates: { link: '%collectionhash', deleted: true }
}
```

@dominictarr thoughts / suggestions ?

**Comment by dominictarr** [comment]
this seems reasonable, but really i think the need to represent a collection of things is pretty generic, we'd be better off not tieing it to photos. (i.e. building some way to do it in general, and then using that to make a photo collection)

**Comment by pfrazee** [comment]
Three thoughts about that:
1. I'll probably need to distinguish in the UI, what kind of collection it is. If we make the type generic, it could apply to photo albums, music playlists, video playlists, user groups, etc. So, we'll at least need a field to distinguish that.
2. I'll probably need to query by collection type as well. For instance, to make a page of image collections.
3. It's hard to say how generic the collection will be without knowing more about the content it'll contain. We may end up with a complex definition with edge-cases for each different use.

What are the merits of making the type-label generic, vs using a common pattern for collections?

**Comment by dominictarr** [comment]
the patterns I am seeing here is just a editable object. you can update keys, and you can move things in arrays. that could apply to a wide variety of things, but probably shouldn't be related to the type, but some extra metadata. it's a mutable data document.

**Comment by pfrazee** [comment]
`ImageList` vs `List<Image>`. Are these patterns that we should formalize with generic message types, or are they patterns that we should reuse across specific types? What's the value of a generic type ?

SSB's native indexes will be more useful in the case of `ImageList`.

**Comment by pfrazee** [comment]
It's more accurate to say, `ImageList` vs `List`. SSB doesnt have any formal way to specify the inner type.

**Comment by dominictarr** [comment]
oh we could totally have a type that was `doc:photos` but i'm not convinced that this should be based on the type. instead probably it should be about links. like, root + update links. and have a property on the root that activates it, `mutable: true`, something like that. This could also work for the package manager. The package is a collection of versions, and the photo collection is a collection of photos.

**Comment by pfrazee** [comment]
Agree about the links. This schema's links are very generic already, and can be applied to lists and documents. The links seem similar to Golang's interfaces, a signature based on the structure.

```
Document interface {
  updates MsgLink
}
List interface {
  includes Links
  excludes Links
}
```

About the type, I'm also unconvinced that we should be specifying complex types in them. I look at types like the table-name in relational databases, as high-level descriptions of the content. I don't see a lot of value in making them more fine-grained.
